### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by felixhirt** [beakona/AutoInterface#10]
After i made a branch of the repo to include some functions/fix some bugs (will make separate issues/pull requests for these) it re-formated all the files because unfortunately, my visual studio settings are setup differently. I would suggest to add an .editorconfig file.

**Comment by beakona** [comment]
I've added .editorconfig with root="true"... I wasn't aware I use custom settings.. feel free to change it as you think it should look like...

**Comment by felixhirt** [comment]
@beakona thx, i will try to find settings that match. I assume you have default settings in VisualStudio then? (Mine are custom, but i never use them anymore because i use .editorconfig everywhere)
