### ISSUE TITLE
Add <IsRoslynComponent>true</IsRoslynComponent> to .csproj

### ISSUE THREAD

**Issue by felixhirt** [beakona/AutoInterface#11]
To facilitate debugging of the source generator, it should have the <IsRoslynComponent>true</IsRoslynComponent> msbuild property (https://www.reddit.com/r/csharp/comments/mqzc4r/source_generators_has_anyone_figured_out_the_new/)

**Comment by beakona** [comment]
I've edited msbuild config and changed debug target... it works like a charm in both VS 2019 and VS 2022 preview..
Sorry for delay, I am on vacation right now...
