### ISSUE TITLE
ObsoleteAttribute inheritance

### ISSUE THREAD

**Issue by amoraller** [beakona/AutoInterface#18]
Nice source generator. Thanks.

If i want delegate implementation to interface with Obsolete methods, i have compilation warnings CS0618. 
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0618?f1url=%3FappId%3Droslyn%26k%3Dk(CS0618)

For example, i want delegate Nlog.ILogger implmentation.

NLog source coge:

        /// <summary>
        /// Writes the diagnostic message at the <c>Debug</c> level using the specified parameters.
        /// </summary>
        /// <param name="message">A <see langword="string" /> containing format items.</param>
        /// <param name="args">Arguments to format.</param>
        [MessageTemplateFormatMethod("message")]
        void Debug([Localizable(false)][StructuredMessageTemplate] string message, params object[] args);

        /// <summary>
        /// Writes the diagnostic message and exception at the <c>Debug</c> level.
        /// </summary>
        /// <param name="message">A <see langword="string" /> to be written.</param>
        /// <param name="exception">An exception to be logged.</param>
        /// <remarks>This method was marked as obsolete before NLog 4.3.11 and it may be removed in a future release.</remarks>
        [Obsolete("Use Debug(Exception exception, string message) method instead. Marked obsolete with v4.3.11")]
        [EditorBrowsable(EditorBrowsableState.Never)]
        void Debug([Localizable(false)] string message, Exception exception);

     
        /// <summary>

Generated code:

        void NLog.ILogger.Debug(string message, params object[] args) => this._nlogImpl.Debug(message, args);

        void NLog.ILogger.Debug(string message, System.Exception exception) => this._nlogImpl.Debug(message, exception);

![image](https://github.com/beakona/AutoInterface/assets/7438667/647d0379-1887-4c46-b143-35eba7823a54)

I think, we want nesting Obsolete attribute.

**Comment by beakona** [comment]
As I understood the real cause of the problem, the ObsoleteAttribute has Inherited=false and a copy of that attribute should be added to the generated source so compiler would not generate warning.
It seems the correct aproach would be to add an additional attribute PassthroughAttributes="Obsolete" (that is the list of attributes). In that case Obsolete would be forwarded by default, but anyone could change that behaviour for other attributes.

I don't have enough free time at the moment and will try to solve this and [another issue](https://github.com/beakona/AutoInterface/issues/17) by the end of this year.

**Comment by beakona** [comment]
I've made nuget prerelease package [1.0.30-pre](https://www.nuget.org/packages/BeaKona.AutoInterfaceGenerator/1.0.30-pre) that should fix this issue.

**Comment by amoraller** [comment]
thanks. It work for me.
