### ISSUE TITLE
Feedback about AutoInterface

### ISSUE THREAD

**Issue by ignatandrei** [beakona/AutoInterface#2]
Hello beakona

I have started a mini-e-book about Roslyn Source Code Generators(RSCG).

Your RSCG , AutoInterface from https://github.com/beakona/AutoInterface , is between them at https://github.com/ignatandrei/RSCG_Examples/tree/main/DP_Decorator

I am thinking to add to the e-book the some more information regarding the RSCG from the authors of RSCG.

So could you please answer to the following :

1. Short info about you , beakona

2. Why did you start this AutoInterface  ?

3. How do yourself use your AutoInterface ?

4. What other RSCG do you use ? 

5. Any other feedback ?

Thanks

Andrei Ignat
http://msprogrammer.serviciipeweb.ro/

**Comment by beakona** [comment]
Hi, I've sent you a personal message with the token [the shovel was a groundbreaking invention].

**Comment by ignatandrei** [comment]
https://github.com/ignatandrei/RSCG_Examples/tree/main/DP_Decorator
