### ISSUE TITLE
record primary constructor

### ISSUE THREAD

**Issue by tecAmoRaller** [beakona/AutoInterface#22]
Maybe source generator must support primary constructors attributes of record? 

```csharp
partial record LoggerWrapper([property: BeaKona.AutoInterface()] Serilog.ILogger logger) : Serilog.ILogger
{
    //[BeaKona.AutoInterface]
    //private readonly Serilog.ILogger _logger = logger;
}

```

**Comment by beakona** [comment]
I've made [1.0.36-pre](https://www.nuget.org/packages/BeaKona.AutoInterfaceGenerator/1.0.36-pre) prerelease that should work as expected.

**Comment by tecAmoRaller** [comment]
nice. It`s work
