### ISSUE TITLE
Unable to use generator for dotted namespaces

### ISSUE THREAD

**Issue by Dblm0** [beakona/AutoInterface#3]
using 5.0.301 sdk I faced a problem, located in namespace processing.

For some reason, splitted namespace parts could not be processed as IdentifierNameSyntax in IsVerbatim method.
In my case they all are QualifiedNameSyntax so NotSupportedException is thrown.

**Comment by beakona** [comment]
Unfortunately I did not test that case. Simple namespaces are represented as IdentifierNameSyntax elements, dotted namespaces are represented as QualifiedNameSyntax with Left part being another QualifiedNameSyntax and Right part being SimpleNameSyntax. IdentifierNameSyntax is subclass of SimpleNameSyntax so I've broaden base case and implement general case.

**Comment by Dblm0** [comment]
@beakona . Looks like this issue got fixed by your recent commit 986e69971. Thanks!
