### ISSUE TITLE
Derived interface implicit implementation

### ISSUE THREAD

**Issue by Dblm0** [beakona/AutoInterface#6]
Working with derived interfaces, I couldn't find a way to use `AutoInterface` attribute for code generation.

For proper understanding what I want to achieve, I've provided a PR #5 with rough solution to my problem.

**Comment by beakona** [comment]
I've published changes which address following:
1. Fixed bug where backing members would be called multiple times.
2. AutoInterface mechanism can be recursive (default is opt-out). Here is the [link](https://github.com/beakona/AutoInterface/wiki/Examples#recursive-interface-types) to an example.
3. Interface list does not have to be explicit.

**Comment by Dblm0** [comment]
Thanks!
